name: it_jobs
description: A Flutter application displaying IT job offers.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc_patterns: ^0.3.1
  get_it: ^3.0.3
  graphql: ^2.1.0
  json_annotation: ^3.0.0
  pedantic: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.7.2
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true
