name: it_jobs
description: A Flutter application displaying IT job offers.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  graphql: ^2.1.0
  json_annotation: ^3.0.0
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.7.0
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true
