name: it_jobs
description: A Flutter application displaying IT job offers.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc_patterns: ^0.9.0
  get_it: ^7.2.0
  graphql: ^5.0.1
  json_annotation: ^4.4.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  lint: ^1.8.2
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
