name: it_jobs
description: A Flutter application displaying IT job offers.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc_patterns: ^0.6.0
  get_it: ^5.0.1
  graphql: ^3.0.0
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  lint: ^1.3.0
  mockito: ^4.1.3

flutter:
  uses-material-design: true
